name: docker tests
on:
  push:
  pull_request:

  workflow_dispatch:
env:
  IMAGE_NAME: zig-memory-tests
  CONTAINER_NAME: zig-memory-tests-container
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build -t $IMAGE_NAME .

    - name: Run the container
      run: docker run --memory 4g --name $CONTAINER_NAME $IMAGE_NAME

    - name: Push the Docker image
      run: docker push ghcr.io/lf477/$IMAGE_NAME:latest
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Run Docker to build the Docker image and run the container
      #   run: docker compose up --build