name: docker tests
on:
  push:

  workflow_dispatch:
env:
  IMAGE_NAME: lf477/zigmemory
  # ${{ github.repository }}
  CONTAINER_NAME: zig-memory-tests-container
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/$IMAGE_NAME
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    # container:
    #   image: $IMAGE_NAME:latest
    #   credentials:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
    # - id: toLowerCase
    #   run: INPUT=$IMAGE_NAME echo "::set-output name=lowerCaseValue::${INPUT,,}"
    
    - name: Checkout repository
      uses: actions/checkout@v4

    # - name: Build the Docker image
    #   run: docker build -t $IMAGE_NAME_LOCAL .

    - name: Run the container
      run: docker run --name $CONTAINER_NAME $IMAGE_NAME
      # ${{steps.toLowerCase.outputs.lowerCaseValue}}
      # $IMAGE_NAME