name: push to registry
on:
  push:

  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      attestations: write
      pages: write
      id-token: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    
    - name: Build and push Docker image
      id: push
      # f2a1d5e99d037542a71f64918e516c093c6f3fc4
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    
    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1.1.1
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
  
    # - name: Log in to Docker Hub
    #     uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
    #     with:
    #       username: ${{ secrets.DOCKER_USERNAME }}
    #       password: ${{ secrets.DOCKER_PASSWORD }}

    #   - name: Extract metadata (tags, labels) for Docker
    #     id: meta
    #     uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
    #     with:
    #       images: my-docker-hub-namespace/my-docker-hub-repository

    #   - name: Build and push Docker image
    #     id: push
    #     uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
    #     with:
    #       context: .
    #       file: ./Dockerfile
    #       push: true
    #       tags: ${{ steps.meta.outputs.tags }}
    #       labels: ${{ steps.meta.outputs.labels }}
      
      
    #   - name: Generate artifact attestation
    #     uses: actions/attest-build-provenance@v1
    #     with:
    #       subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
    #       subject-digest: ${{ steps.push.outputs.digest }}
    #       push-to-registry: true

    # - name: Push the Docker image
    #   run: |
    #       docker push ghcr.io/lf477/$IMAGE_NAME:latest
    #   env:
    #       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Run Docker to build the Docker image and run the container
      #   run: docker compose up --build