name: docker tests
on:
  push:

  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      attestations: write
      pages: write
      id-token: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      id: push
      # f2a1d5e99d037542a71f64918e516c093c6f3fc4
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  pull_from_registry:
    runs-on: ubuntu-latest

    container:
      image: $REGISTRY/$IMAGE_NAME
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        # ${{ secrets.DOCKERHUB_USERNAME }}
        # ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:

    - name: Run the test
      run: cd /tests && zig build test